$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$music = Join-Path $root "assets\music"
$exts = @(".mp3", ".m4a", ".aac", ".wav", ".ogg", ".flac")
$files = Get-ChildItem -LiteralPath $music -File | Where-Object { $exts -contains $_.Extension.ToLowerInvariant() } | Sort-Object Name
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// AUTO-GENERATED by refresh_music_library.bat")
$lines.Add("window.SEAT_BGM_LIBRARY = [")
foreach ($f in $files) {
  $title = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
  $src = "assets/music/" + $f.Name
  $titleJson = $title | ConvertTo-Json -Compress
  $srcJson = $src | ConvertTo-Json -Compress
  $lines.Add("  { title: $titleJson, src: $srcJson },")
}
$lines.Add("];")
Set-Content -LiteralPath (Join-Path $root "music-library.js") -Value $lines -Encoding UTF8
Write-Host "Updated music-library.js with $($files.Count) track(s)."
