// AUTO-GENERATED by refresh_music_library.bat
window.SEAT_BGM_LIBRARY = [
  { title: "Assarabia", src: "assets/music/Assarabia.m4a" },
  { title: "Come to me", src: "assets/music/Come to me.m4a" },
  { title: "Happy Day", src: "assets/music/Happy Day.m4a" },
  { title: "Morning Rush", src: "assets/music/Morning Rush.m4a" },
];
